const dapil1 = ["Hj. ENNY MINARSIH", "DYAH WULANDARI, S.P.", "HIMAS MUHAMMMADY I. EL HAKIM", "ZAINUDDIN", "MUZAN THOIB, S.Pd.", "NANING HARIYATI", "HAMAS SYAHID IZZUDDIN", "ARIEF HERCAHYANTO", "LILIS SURYANI", "BASUKI ABDUL AZIZ, S.Si."];
const dapil2 = ["ARIF FAHRUDDIN, S.T.", "NAJI ABDURAHMAN BAWAZIER", "HAWATIH", "MOCH. RIDUWAN", "Hj. SULUHWATI, S.T.", "H. EKA SUREZTA", "DINDA NURMALASARI FAHRIDA, S.Hum.", "CHIFRUL SYAICHUDIN, S.T.", "FARIS ABIDIN, S.Pi", "FARHANNAH", "ABDAN FIKRI, S.T., M.T."];
const dapil3 = ["ANING RAHMAWATI, S.T.", "Hj. drg. ENNY YEKTI K", "ZAINAL ABIDIN", "RIZKI WANDA BUDIMAN, S.T.", "Dr. Ir. DIYAN LESMANA, M.M.", "dr. LINA AZIZAH", "BUDI CAHYO WIDODO, S.H.", "MOCH. SUSANTO", "SUTIMI, S.T.", "PINUJI"];
const dapil4 = ["CAHYO SISWO UTOMO, S.T., M.H.", "HERMAWAN, S.T.", "NURUL KHOIRIYAH", "ACHMAD BRANTAS PURNOMO", "dr. AGUNG HENDRO YUWONO, M.Kes.", "Hj. SHANTY OCTAVIA UTAMI, S.T.", "WINARSIH", "IMAM BUDI UTOMO, S.T., M.M.", "DANI SUSANTO, S.T."];
const dapil5 = ["JOHARI MUSTAWAN, S.T.P., M.A.R.S.", "Hj. RAHMAWATI, S.Sos.", "H. ABDUL SOMAD, S.S., M.Ak.", "BAMBANG SETIAWAN", "AMIR SAKIB, S.Pd., M.Pd.I", "IMELDA APRILIANITA, S.T.", "IMAM HANAFI, S.Pd.I.", "H. DENNY ARDIANSYAH, S.E.", "YULI ARYANI", "MOH. HARUN MURSYID ALAMIN, S.E."];

const provinsi = ["Hj. LILIK HENDARWATI", "AHMAD JABIR, S.T., M.T.", "FATKUR ROHMAN, S.T., M.T.", "FARIED, S.H.", "NASTITI WAHYU PRISTIANTI, S.M.", "SULTHONY HARIS MIFTAH, S.H.", "ATIEK SUHARYATI, S.Farm.", "HAMMAD AKRAM"];
const pusat = ["Ir. H. SIGIT SOSIANTOMO", "RENI ASTUTI, S.Si., M.PSDM.", "dr. AGOES KOOSHARTORO, Sp.P.D.(K).", "H. JALALUDDIN ALHAM, S.I.P., M.Hum.", "WAHYU SRIONO", "dr. AUFIYA NAILY", "DIHIN SUPRIYANDINI, S.Farm.", "RUSFIAN EFFENDI, S.M., S.Ag., M.M.", "Drs. MUHAMMAD AZIZ", "HUSIN, S.E."];

export { dapil1, dapil2, dapil3, dapil4, dapil5, pusat, provinsi };
