import Head from "next/head";
import styles from "../styles/Home.module.css";
import Nav from "../components/Nav";
import About from "../components/About";
import Projects from "../components/Projects";
import Blog from "../components/Blog";
import Form from "../components/Form";
import Footer from "../components/Footer";

export default function Home() {
	const scrollToProjects = (elId) => {
		window.scrollTo({
			top: document.getElementById(elId).offsetTop - 60,
			behavior: "smooth",
		});
	};

	const handleNavClick = (e) => {
		e.preventDefault();
		const goto = e.target.getAttribute("goto");
		setTimeout(() => {
			scrollToProjects(goto);
		}, 100);
	};

	return (
		<div className=" bg-darkPurple flex flex-col mx-auto">
			<Head>
				<title>Dirman Dev</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/dirmandev.ico" />
			</Head>

			<header></header>
			<Nav handleNavClick={handleNavClick} />
			<div className={styles.container}>
				<About />
				<Projects />
				{/* <Blog /> */}
				<Form />
				<Footer />
			</div>
		</div>
	);
}
