import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Nav from '../components/Nav'
import About from '../components/About'
import Projects from '../components/Projects'
import Blog from '../components/Blog'
import Form from '../components/Form'
import Footer from '../components/Footer'

export default function Home() {
  return (
    <div className="flex flex-col items-center">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header></header>
      <Nav />
      <div className={styles.container}>
        <About />
        <Projects />
        <Blog />
        <Form />
        <Footer/>
      </div>
    </div>
  );
}
